
import java.awt.Color;

public class CalculeSalary extends javax.swing.JFrame {

    /**
     * Creates new form CalculeSalary
     */
    public CalculeSalary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        Top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Production = new javax.swing.JButton();
        Manutention = new javax.swing.JButton();
        Representation = new javax.swing.JButton();
        Exitbtn = new javax.swing.JButton();
        Ventebtn = new javax.swing.JButton();
        Choix = new javax.swing.JLabel();
        Bienvenue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CalcSalary V1.0");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/icons/ico.png")).getImage());
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1016, 386));

        Top.setBackground(new java.awt.Color(16, 31, 54));

        jLabel1.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("For Your Company");

        jLabel2.setFont(new java.awt.Font("Montserrat Medium", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CalcSalary");

        jLabel3.setFont(new java.awt.Font("Gabriola", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("By Chems Eddine Nemeur");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Online_Money_Transfer_100px.png"))); // NOI18N

        javax.swing.GroupLayout TopLayout = new javax.swing.GroupLayout(Top);
        Top.setLayout(TopLayout);
        TopLayout.setHorizontalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1)
                        .addGap(0, 653, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
            .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopLayout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );
        TopLayout.setVerticalGroup(
            TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TopLayout.createSequentialGroup()
                        .addContainerGap(50, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3))
            .addGroup(TopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TopLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );

        Production.setBackground(new java.awt.Color(255, 255, 255));
        Production.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Production.setForeground(Top.getBackground());
        Production.setText("Production");
        Production.setToolTipText("Calculer le salaire d'employe de la Production");
        Production.setBorder(null);
        Production.setBorderPainted(false);
        Production.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Production.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ProductionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ProductionMouseExited(evt);
            }
        });
        Production.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProductionActionPerformed(evt);
            }
        });

        Manutention.setBackground(new java.awt.Color(255, 255, 255));
        Manutention.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Manutention.setForeground(Top.getBackground());
        Manutention.setText("Manutention");
        Manutention.setToolTipText("Calculer le salaire d'employe de la Manutention");
        Manutention.setBorder(null);
        Manutention.setBorderPainted(false);
        Manutention.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Manutention.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManutentionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManutentionMouseExited(evt);
            }
        });
        Manutention.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManutentionActionPerformed(evt);
            }
        });

        Representation.setBackground(new java.awt.Color(255, 255, 255));
        Representation.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Representation.setForeground(Top.getBackground());
        Representation.setText("Representation");
        Representation.setToolTipText("Calculer le salaire d'employe de la Representation");
        Representation.setBorder(null);
        Representation.setBorderPainted(false);
        Representation.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Representation.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RepresentationMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RepresentationMouseExited(evt);
            }
        });
        Representation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepresentationActionPerformed(evt);
            }
        });

        Exitbtn.setBackground(new java.awt.Color(255, 255, 255));
        Exitbtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Exitbtn.setForeground(Top.getBackground());
        Exitbtn.setText("Exit");
        Exitbtn.setBorder(null);
        Exitbtn.setBorderPainted(false);
        Exitbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Exitbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitbtnMouseExited(evt);
            }
        });
        Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitbtnActionPerformed(evt);
            }
        });

        Ventebtn.setBackground(new java.awt.Color(255, 255, 255));
        Ventebtn.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 16)); // NOI18N
        Ventebtn.setForeground(Top.getBackground());
        Ventebtn.setText("Vente");
        Ventebtn.setToolTipText("Calculer le salaire d'employe de la Vente");
        Ventebtn.setBorder(null);
        Ventebtn.setBorderPainted(false);
        Ventebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Ventebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VentebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentebtnMouseExited(evt);
            }
        });
        Ventebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VentebtnActionPerformed(evt);
            }
        });

        Choix.setFont(new java.awt.Font("Montserrat Medium", 0, 16)); // NOI18N
        Choix.setForeground(Top.getBackground());
        Choix.setText("Choisir une Branche : ");

        Bienvenue.setFont(new java.awt.Font("Montserrat Medium", 0, 14)); // NOI18N
        Bienvenue.setForeground(Top.getBackground());
        Bienvenue.setText("Bienvenue sur CalcSalary!");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(Production, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(Manutention, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(Representation, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(Ventebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Choix)
                            .addComponent(Bienvenue))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bienvenue)
                .addGap(17, 17, 17)
                .addComponent(Choix)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Representation, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ventebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Manutention, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Production, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(Exitbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    Color Back = new Color(16,31,54);
    Color Exiteclr = new Color(252, 40, 72);
    
    private void ProductionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProductionActionPerformed

        new Production().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ProductionActionPerformed

    private void ManutentionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManutentionActionPerformed
       new Manutention().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ManutentionActionPerformed

    private void RepresentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepresentationActionPerformed
       new Representation().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_RepresentationActionPerformed

    private void ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitbtnActionPerformed
       System.exit(0);
    }//GEN-LAST:event_ExitbtnActionPerformed

    private void VentebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VentebtnActionPerformed
      new Vente().setVisible(true);
      this.dispose();
    }//GEN-LAST:event_VentebtnActionPerformed

    private void VentebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentebtnMouseEntered
       Ventebtn.setBackground(Back);
       Ventebtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_VentebtnMouseEntered

    private void VentebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentebtnMouseExited
        Ventebtn.setBackground(Color.WHITE);
        Ventebtn.setForeground(Back);
    }//GEN-LAST:event_VentebtnMouseExited

    private void RepresentationMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepresentationMouseEntered
        Representation.setBackground(Back);
        Representation.setForeground(Color.WHITE);
    }//GEN-LAST:event_RepresentationMouseEntered

    private void RepresentationMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RepresentationMouseExited
        Representation.setBackground(Color.WHITE);
        Representation.setForeground(Back);
    }//GEN-LAST:event_RepresentationMouseExited

    private void ManutentionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManutentionMouseEntered
        Manutention.setBackground(Back);
        Manutention.setForeground(Color.WHITE);
    }//GEN-LAST:event_ManutentionMouseEntered

    private void ManutentionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManutentionMouseExited
        Manutention.setBackground(Color.WHITE);
        Manutention.setForeground(Back);
    }//GEN-LAST:event_ManutentionMouseExited

    private void ProductionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductionMouseEntered
        Production.setBackground(Back);
        Production.setForeground(Color.WHITE);
    }//GEN-LAST:event_ProductionMouseEntered

    private void ProductionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductionMouseExited
        Production.setBackground(Color.WHITE);
        Production.setForeground(Back);
    }//GEN-LAST:event_ProductionMouseExited

    private void ExitbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseEntered
        Exitbtn.setBackground(Exiteclr);
    }//GEN-LAST:event_ExitbtnMouseEntered

    private void ExitbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitbtnMouseExited
        Exitbtn.setBackground(Color.WHITE);
    }//GEN-LAST:event_ExitbtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculeSalary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculeSalary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenue;
    private javax.swing.JLabel Choix;
    private javax.swing.JButton Exitbtn;
    private javax.swing.JButton Manutention;
    private javax.swing.JButton Production;
    private javax.swing.JButton Representation;
    private javax.swing.JPanel Top;
    private javax.swing.JButton Ventebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
